### ISSUE TITLE
Getting a pad block corrupted error 

### ISSUE THREAD

**Issue by Prasadnair** [claboran/ForceDotNetJwtCompanion#19]
Hello @claboran,

I'm facing an issue while validating the private key and passphrase. Please advise what would be the root cause of the error "pad block corrupted"

at Org.BouncyCastle.Crypto.Paddings.Pkcs7Padding.PadCount(Byte[] input)
   at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff)
   at Org.BouncyCastle.Crypto.BufferedBlockCipher.DoFinal(Byte[] input, Int32 inOff, Int32 inLen)
   at Org.BouncyCastle.OpenSsl.PemUtilities.Crypt(Boolean encrypt, Byte[] bytes, Char[] password, String dekAlgName, Byte[] iv)
   at Org.BouncyCastle.OpenSsl.PemReader.ReadPrivateKey(PemObject pemObject)
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
   at ForceDotNetJwtCompanion.Util.KeyHelpers.CreatePrivateKeyWrapperWithPassPhrase(String key, String passphrase)
   at ForceDotNetJwtCompanion.JwtAuthenticationClient.<JwtPrivateKeyAsync>d__29.MoveNext().

Note:
we are renewing our certificate.

**Comment by claboran** [comment]
@Prasadnair: How did you generate the key? Would be good to have the version too.

**Comment by claboran** [comment]
@Prasadnair Did you have the --traditional flag added?
openssl genrsa -des3 -traditional -passout pass:secret -out server-new.pass.key 2048

**Comment by Prasadnair** [comment]
we are using external certificate. I upload the public key and validated using the private key. 

private key below
-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----

**Comment by Prasadnair** [comment]
got another issue when tried with another private which I received form the platform team.
System.InvalidCastException: 'Unable to cast object of type 'Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters' to type 'Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair

any insights on this?

**Comment by Prasadnair** [comment]
Pad block corrupted error again 
at Org.BouncyCastle.Crypto.Paddings.Pkcs7Padding.PadCount(Byte[] input)
   at Org.BouncyCastle.Crypto.Paddings.PaddedBufferedBlockCipher.DoFinal(Byte[] output, Int32 outOff)
   at Org.BouncyCastle.Crypto.BufferedBlockCipher.DoFinal(Byte[] input, Int32 inOff, Int32 inLen)
   at Org.BouncyCastle.OpenSsl.PemUtilities.Crypt(Boolean encrypt, Byte[] bytes, Char[] password, String dekAlgName, Byte[] iv)
   at Org.BouncyCastle.OpenSsl.PemReader.ReadPrivateKey(PemObject pemObject)
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
   at ForceDotNetJwtCompanion.Util.KeyHelpers.CreatePrivateKeyWrapperWithPassPhrase(String key, String passphrase)
   at ForceDotNetJwtCompanion.JwtAuthenticationClient.<JwtPrivateKeyAsync>d__29.MoveNext()

**Comment by Prasadnair** [comment]
Final Update:
I followed the below steps

Generate a private key, and store it in a file called server.key
    openssl genrsa -des3 -passout pass:secret -out C:\\CT\SFCert\server.pass.key 2048
    openssl rsa -passin pass:secret -in C:\CT\SFCert\server.pass.key -out C:\CT\SFCert\server.key
Generate a certificate signing request using the server.key file. Store the certificate signing request in a file called server.csr. Enter information about your company when prompted.
    openssl req -new -key C:\CT\SFCert\server.key -out C:\FCT\SFCert\server.csr
Generate a self-signed digital certificate from the server.key and server.csr files. Store the certificate in a file called server.crt
    openssl x509 -req -sha256 -days 500 -in C:\CT\SFCert\server.csr -signkey C:\CT\SFCert\server.key -out C:\CT\SFCert\server.crt

now I'm getting this error:
System.InvalidCastException: 'Unable to cast object of type 'Org.BouncyCastle.Crypto.Parameters.RsaPrivateCrtKeyParameters' to type 'Org.BouncyCastle.Crypto.AsymmetricCipherKeyPair'.'

**Comment by Prasadnair** [comment]
I created the crt using OpenSSL 1.1 with 32 bit. it got success.

how this can be achieved using OpenSSL 3.0  Please advise

**Comment by claboran** [comment]
@Prasadnair I need to check how I can get this to work for OpenSSL 3. I know that this is an long term issue.

**Comment by Prasadnair** [comment]
Hello @claboran ,

i quickly checked the OpenSSL 3. I believe the below code won't work in method :CreatePrivateKeyWrapperWithPassPhrase class: KeyHelpers.cs

var pemReader = new PemReader(new StringReader(key), new PasswordFinder(passphrase));
var pem = (AsymmetricCipherKeyPair)pemReader.ReadObject();
var param = (RsaPrivateCrtKeyParameters)pem.Private;

return new PrivateKeyWrapper
{
    Modulus = param.Modulus,
  Exponent = param.Exponent
};

I tweaked the code as below and it works fine. Please take a look and provide your feedback

public static PrivateKeyWrapper CreatePrivateKeyWrapperWithPassPhrase(string key, string passphrase)
{
    //var pemReader = new PemReader(new StringReader(key), new PasswordFinder(passphrase));
    //var pem = (AsymmetricCipherKeyPair)pemReader.ReadObject();
    //var param = (RsaPrivateCrtKeyParameters)pem.Private;

    //return new PrivateKeyWrapper
    //{
    //    Modulus = param.Modulus,
    //    Exponent = param.Exponent
    //};

    using var reader = new StringReader(key);

    PemReader pemReader = string.IsNullOrEmpty(passphrase)
        ? new PemReader(reader)
        : new PemReader(reader, new PasswordFinder(passphrase));

    object keyObject = pemReader.ReadObject();

    RsaPrivateCrtKeyParameters rsaPrivateKey;

    if (keyObject is AsymmetricCipherKeyPair keyPair)
    {
        // PKCS#8 style key
        rsaPrivateKey = (RsaPrivateCrtKeyParameters)keyPair.Private;
    }
    else if (keyObject is RsaPrivateCrtKeyParameters rsaParams)
    {
        // PKCS#1 style key
        rsaPrivateKey = rsaParams;
    }
    else
    {
        throw new InvalidCastException($"Unsupported key format: {keyObject?.GetType().FullName}");
    }

    return new PrivateKeyWrapper
    {
        Modulus = rsaPrivateKey.Modulus,
        Exponent = rsaPrivateKey.Exponent
    };
}

**Comment by claboran** [comment]
@Prasadnair will look into it. Sorry for the late response. I had a lot of other topics to do.
